sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lchase/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lchase/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-docker-react"
  env: "Udemydockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-121859637847"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY